### ISSUE TITLE
Example login request not working

### ISSUE THREAD

**Issue by olirice** [iozozturk/scalongo#1]
The example README request queries by username but line 57 of AuthController.scala searches the user collection using the 'findByUsername' method which causes a 403 response.
## AuthController.scala

userService.findByEmail(loginData.username).map((user: User)
## Resolution

userService.findByUsername(loginData.username).map((user: User)

**Comment by iozozturk** [comment]
Thank you for pointing out Oliver. My first intention was to use email for login but then went with the username. Anyway, your resolution looks good, fixed that. 

7819c5661d89b7973a86120d228c84d8695d38c8
